### ISSUE TITLE
Not working with Glaxy S4 Active 

### ISSUE THREAD

**Issue by Spodi** [bbukowski/NotifCount#1]
Looks like it doesnt do anything on 4.2.2 with the s4 active stock rom... Can i do anything to help you solving this?

**Comment by sioban** [comment]
Same for Galaxy S4, CM 11.2 (KK 4.4.4).
Would love badge count for the status bar (and a regroup function for the notification bar developped)

**Comment by bbukowski** [comment]
Thanks for response. I have published a new version (v1.0.2). It is now possible to create a test notification. Please try it out, and let me know.

@Spodi I will set up a device with 4.2.2 and will check that.

@sioban CM11 has that feature built in. You won't need this module.

FYI: Every notification can have a number. This module is relying on this number. But there are some apps, that won't set that number at all. I am planning to work around that.

**Comment by sioban** [comment]
Really ?
I think it's activated (Display number of pending notifications) but it does nothing :(

**Comment by Spodi** [comment]
Ok, the Notification test is working. It displays a small 5 with the icon. Maybe you should clarify, that this module doesn't automatically group notification icons and only works if the  sending App does the grouping and counting itself. My bad for misunderstanding that. :-)
By the way, most of my Apps dont do that, not even WhatsApp or Google Play (multiple installs = multiple icons) :-(

**Comment by bbukowski** [comment]
Checkout version 1.1 please. I have implemented a workaround far apps not setting a number to notification.

**Comment by Spodi** [comment]
Cant get it to work with 1.1 :-(
Both tests wont show a badge anymore (Doesnt matter if whitelisted or not) even after reboot
EDIT: Exraction from exposed error log:

``` javascript
2014-08-12 21:19:38  Loading modules from /data/app/de.bbukowski.notifcount-1.apk
2014-08-12 21:19:38    Loading class de.bbukowski.notifcount.XposedMod
2014-08-12 21:19:38   
java.lang.NoSuchMethodError: android.app.Notification$InboxStyle#buildStyled(android.app.Notification)#exact
    at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:179)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:129)
    at de.bbukowski.notifcount.XposedMod.hookNotificationInboxStyle(XposedMod.java:123)
    at de.bbukowski.notifcount.XposedMod.initZygote(XposedMod.java:52)
    at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:437)
    at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
    at dalvik.system.NativeStart.main(Native Method)
[next module starting] 
```

**Comment by bbukowski** [comment]
Thank you very much for your help. Please check out version 1.1.1.

**Comment by Spodi** [comment]
Working, at least with test notification. Didnt test others, but i think it should work 😊
